config/routes.rb
RestaurantApp::Application.routes.draw do


  resources :categories

  get "users/dashboard"
  resources :reservations
  resources :categories

  devise_for :users

  authenticated :user do
    root :to => "users#dashboard", :as => "authenticated_root"
  end
  
  root "welcome#index"

  resources :restaurants do 
    resources :reservations
    resources :stars
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :restaurants

  default_scope lambda { order('categories.name') }
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant
	validates_presence_of :email, :requested_date
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates_presence_of :name
	mount_uploader :image, ImageUploader
	mount_uploader :menu, MenuUploader

	belongs_to :user
	has_many :reservations, :dependent => :destroy
	has_many :stars
	has_many :starred_by, through: :stars, source: :user

	accepts_nested_attributes_for :reservations
  
  has_and_belongs_to_many :categories

	validates_presence_of :name, :user_id

	def full_address
		address = ""
		address << self.street unless self.street == ""
		address << ' ' + self.city unless self.city == ""
		address << ' ' + self.state unless self.state == ""
		address << ' ' + self.zipcode unless self.zipcode == ""
		return address
	end

	attr_reader :category_tokens

	def category_tokens=(ids)
		self.category_ids = ids.split(",")
	end



end

app/models/star.rb
class Star < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :restaurants
    has_many :stars

    has_many :starred_restaurants, through: :stars, source: :restaurant


    validates_presence_of :email, :name

    def owner
    	self.role == 'owner'
    end

    def patron
    	self.role == 'patron'
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all

		@categories = Category.where("name like ?", "%#{params[:q]}%")
		respond_to do |format|
			format.html
			format.json {render :json => @categories}
		end

	end

	def show
		@category = Category.find(params[:id])
	end

	# def search
	# 	arr = [1,2]
	# 	rs = Restaurant.joins(:categories).where(:categories => {:id => arr.sort})
	# 	@list = rs.find_all{|r| r.categories.map(&:id) == arr.sort}
	# 	@list.uniq
	# end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	before_filter :authenticate_user!
	before_filter :credentials_filter, :only => [:edit, :destroy]


	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(restaurant_params)
		@restaurant.user = current_user

		if @restaurant.save
			redirect_to @restaurant
		else
			render 'new'
		end
	end

	def show
		@restaurant = Restaurant.find(params[:id])
		@can_edit = @restaurant.user == current_user
	end

	def index
		@restaurants = Restaurant.find(:all)
	end

	def edit
		@restaurant = Restaurant.find(params[:id])

	end

	def update
		@restaurant = Restaurant.find(params[:id])

		if @restaurant.update(restaurant_params)
			redirect_to @restaurant
		else
			render 'edit'
		end

	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy

		redirect_to restaurants_path		
	end

	private
		def restaurant_params
			params.require(:restaurant).permit(:name, :description, :street, :city, :state, :zipcode, :phone, :image, :remote_image_url, :menu, :category_tokens, :category_ids => [])
		end

	def credentials_filter
		user = Restaurant.find(params[:id]).user
		unless user == current_user
			flash[:message] = "Please login with the appropiate credentials"
			redirect_to :root
		end
	end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
	def new
		@restaurant = Restaurant.find(params[:restaurant_id])
		@star = Star.new
	end

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@star = @restaurant.stars.new
    	@star.user_id = current_user.id
		
		if @star.save
			respond_to do |format|
      		#flash[:notice] = "You have successfully starred this restaurant"
      		format.html { redirect_to restaurant_path(@restaurant) }
      		format.js
  			end
    	else
      		render 'star_restaurant'
    	end
	end

	def destroy
		@restaurant = Restaurant.find(params[:restaurant_id])
    	@star = Star.find(params[:id])
    	@star.destroy
    	respond_to do |format|
          #flash[:notice] = "You have successfully unstarred this restaurant"
          format.html {redirect_to restaurant_path(@restaurant)}
          format.js
        end
  end


end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
  	@x = 1
  	@title = "Index"
  end

  def show
  end

  def welcome
  	@title = "Welcome"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
  	#@restaurants = Restaurant.find_by_user_id(current_user) #this is the old way
  	@restaurants = Restaurant.where(:user => current_user) #using active relations, read about 'like'
  	@starred_by_user = Star.where(:user_id => current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def mark_required(object, attribute)
    "*" if object.class.validators_on(attribute).map(&:class).include? ActiveRecord::Validations::PresenceValidator
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
require 'uri'
module RestaurantsHelper
	def gmap_url(restaurant)
		url = "http://maps.googleapis.com/maps/api/staticmap?"
		url << "center=" + URI.escape(restaurant.full_address)
		url << "&markers=" + "color:red|" + URI.escape(restaurant.full_address)
		url << "&zoom=14"
		url << "&size=200x200"
		url << "&sensor=false"
		url << "&key=#{ ENV['GMAPS_API_KEY'] }"
		return url
	end

	def all_restaurants_gmap(restaurants)
		url = "http://maps.googleapis.com/maps/api/staticmap?"
		url << "center=" + URI.escape(@restaurants.first.zipcode)
		url << "&zoom=14"
		url << "&size=400x400"
		url << "&sensor=false"
		url << "&key=#{ ENV['GMAPS_API_KEY'] }"
		url << "&markers=color:red"

		@restaurants.each do |restaurant|
			url << '|' + "#{url_encode(restaurant.full_address)}" unless restaurant.full_address == ""
		end

		return url
	end

end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, :html => {:multipart => true, 'data-validate' => "parsley"} do |f| %>
<% if @restaurant.errors.any? %>
  <div id = "error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited
      this restaurant from being saved:</h2>
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
	<p>
		<%= f.label :name %><%= mark_required(@restaurant, :name) %><br>
		<%= f.text_field :name, required: true %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>

	<p>
		<%= f.label :category_tokens, "Categories" %><br>
		<%= f.text_field :category_tokens, "data-pre" => @restaurant.categories.to_json %>
	</p>

<!--  	<p>
		<%= hidden_field_tag "restaurant[category_ids][]", nil%>
		<%= f.label :category %><br>
		<% Category.all.each do |category| %>
		<%= check_box_tag "restaurant[category_ids][]", category.id, @restaurant.category_ids.include?(category.id), id: dom_id(category) %>
		<%= label_tag dom_id(category), category.name  %><br>
		<% end %>
	</p> -->


	<p>
		<%= f.label :street %><br>
		<%= f.text_field :street %>
	</p>
	<p>
		<%= f.label :city %><br>
		<%= f.text_field :city %>
	</p>
		<p>
		<%= f.label :state %><br>
		<%= f.text_field :state %>
	</p>

	<p>
		<%= f.label :zipcode %><br>
		<%= f.text_field :zipcode %>
	</p>
	<p>
		<%= f.label :phone %><br>
		<%= f.text_field :phone %>
	</p>
	<p>
		<%= f.file_field :image %>
	</p>
	<p>
		<%= f.label :remote_image_url, "or image URL" %>
		<%= f.text_field :remote_image_url %>
	</p>
	<p><%=f.label :menu%>
	<%= f.file_field :menu %>
	</p>

	<table id="schedule">
		<caption>Restaurant schedule</caption>
		<tr>
			<th>day</th>
			<th>opening</th>
			<th>closing</th>
			<th>closed</th>	
		</tr>
		
		<tr>
			
			<td><%= 'monday' %></td>
			<td><%= f.time_select :monday_open_at, {:ampm => true, :default => {:hour => '6', :minute => '00'}} %></td>
			<td><%= f.time_select :monday_close_at, {:ampm => true, :default => {:hour => '22', :minute => '00'}} %></td>
			<td><%= check_box_tag "closed" %></td>
		</tr>

		<tr>
			
			<td><%= 'tuesday' %></td>
			<td><%= f.time_select :tuesday_open_at, {:ampm => true, :default => {:hour => '6', :minute => '00'}} %></td>
			<td><%= f.time_select :tuesday_close_at, {:ampm => true, :default => {:hour => '22', :minute => '00'}} %></td>
			<td><%= check_box_tag "closed" %></td>
		</tr>
		<tr>
			
			<td><%= 'wednesday' %></td>
			<td><%= f.time_select :wednesday_open_at, {:ampm => true, :default => {:hour => '6', :minute => '00'}} %></td>
			<td><%= f.time_select :wednesday_close_at, {:ampm => true, :default => {:hour => '22', :minute => '00'}} %></td>
			<td><%= check_box_tag "closed" %></td>
		</tr>

		<tr>
			
			<td><%= 'thursday' %></td>
			<td><%= f.time_select :thursday_open_at, {:ampm => true, :default => {:hour => '6', :minute => '00'}} %></td>
			<td><%= f.time_select :thursday_close_at, {:ampm => true, :default => {:hour => '22', :minute => '00'}} %></td>
			<td><%= check_box_tag "closed" %></td>
		</tr>
		<tr>
			
			<td><%= 'friday' %></td>
			<td><%= f.time_select :friday_open_at, {:ampm => true, :default => {:hour => '6', :minute => '00'}} %></td>
			<td><%= f.time_select :friday_close_at, {:ampm => true, :default => {:hour => '22', :minute => '00'}} %></td>
			<td><%= check_box_tag "closed" %></td>
		</tr>

		<tr>
			
			<td><%= 'saturday' %></td>
			<td><%= f.time_select :saturday_open_at, {:ampm => true, :default => {:hour => '6', :minute => '00'}} %></td>
			<td><%= f.time_select :saturday_close_at, {:ampm => true, :default => {:hour => '22', :minute => '00'}} %></td>
			<td><%= check_box_tag "closed" %></td>
		</tr>	

		<tr>
			
			<td><%= 'sunday' %></td>
			<td><%= f.time_select :sunday_open_at, {:ampm => true, :default => {:hour => '6', :minute => '00'}} %></td>
			<td><%= f.time_select :sunday_close_at, {:ampm => true, :default => {:hour => '22', :minute => '00'}} %></td>
			<td><%= check_box_tag "closed" %></td>
		</tr>		

		
	</table>
	
	
	<p>
		<%= f.submit %><br>
	</p>



	<% end %>

<% content_for :token_input_caller do %>
  <script type='text/javascript'>
    $(function () {
		$("#restaurant_category_tokens").tokenInput("/categories.json", {
			crossDomain: false,
			prePopulate: $("#restaurant_category_tokens").data("pre"),
			theme: "facebook"
		})
	});
  </script>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>
<%= render 'form' %>
<%= link_to "Back", restaurants_path %>	

app/views/restaurants/index.html.erb
<div>
<h1>Listing restaurants</h1>
<input class="navbar-search" class="pull-right" type="search" placeholder="Find a restaurant"/ >
<hr/>
</div>

<table class='table table-striped'>
	<tr>
		<th>Pic</th>
		<th>Name</th>
		<th>Description</th>
		<th>Menu</th>
		<th></th>
		<th></th>
	</tr>

	<% @restaurants.each do |restaurant| %>
		<tr>
			<td><%=image_tag restaurant.image_url(:thumb).to_s %></td>
			<td><%= restaurant.name%></td>
			<td><%= restaurant.description %> </td>
			
			<td><%= link_to 'Show', restaurant %></td>
			<td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
			<td><%= link_to 'Destroy', restaurant_path(restaurant),
			method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
		<% full_address = restaurant.street + ' ' + restaurant.city + ' ' +restaurant.state + ' ' + restaurant.zipcode
 %>

	<% end %>
</table>


<%= link_to "New Restaurant", new_restaurant_path %>

<p><%= image_tag all_restaurants_gmap(@restaurants) %></p>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to "Back", restaurants_path %>

app/views/restaurants/show.html.erb
<%= image_tag @restaurant.image_url(:masthead).to_s %>

 <%= render 'stars/star_restaurant' %> 
 
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Categories:</strong>
  <% @restaurant.categories.each do |category| %>
  <%= category.name %>
  <% end %>

</p>

<p>
<% if @restaurant.menu.present? %>
	<strong>Menu:</strong>
	<%=link_to "Menu", @restaurant.menu_url  %>
<% end %>
</p>


<%= image_tag gmap_url(@restaurant) %>



<br>

<%= link_to "Back", restaurants_path %>


<% if @restaurant.user == current_user %>
	| <%= link_to 'Edit', edit_restaurant_path(@restaurant) %>

	| <%= link_to "Reservations",   restaurant_reservations_path(@restaurant) %>

<% else %>

	| <%= link_to "Make a reservation", new_restaurant_reservation_path(@restaurant) %>

<% end %>

app/views/restaurants/show.js.erb
$('#remove_star').hide;//.after(<%= j removed!%>);
$('#add_star').hide;//.after(<%= j added!%>);