config/routes.rb
RestaurantApp::Application.routes.draw do


  resources :categories

  get "users/dashboard"
  resources :reservations
  resources :categories

  devise_for :users

  authenticated :user do
    root :to => "users#dashboard", :as => "authenticated_root"
  end
  
  root "welcome#index"

  resources :restaurants do 
    resources :reservations
    resources :stars
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :restaurants

  default_scope lambda { order('categories.name') }
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant
	validates_presence_of :email, :requested_date
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates_presence_of :name
	mount_uploader :image, ImageUploader
	mount_uploader :menu, MenuUploader

	belongs_to :user
	has_many :reservations, :dependent => :destroy
	has_many :stars
	has_many :starred_by, through: :stars, source: :user

	accepts_nested_attributes_for :reservations
  
  has_and_belongs_to_many :categories

	validates_presence_of :name, :user_id

	def full_address
		address = ""
		address << self.street unless self.street == ""
		address << ' ' + self.city unless self.city == ""
		address << ' ' + self.state unless self.state == ""
		address << ' ' + self.zipcode unless self.zipcode == ""
		return address
	end

	attr_reader :category_tokens

	def category_tokens=(ids)
		self.category_ids = ids.split(",")
	end



end

app/models/star.rb
class Star < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :restaurants
    has_many :stars

    has_many :starred_restaurants, through: :stars, source: :restaurant


    validates_presence_of :email, :name

    def owner
    	self.role == 'owner'
    end

    def patron
    	self.role == 'patron'
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end





end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all

		@categories = Category.where("name like ?", "%#{params[:q]}%")
		respond_to do |format|
			format.html
			format.json {render :json => @categories}
		end

	end

	def show
		@category = Category.find(params[:id])
	end

	# def search
	# 	arr = [1,2]
	# 	rs = Restaurant.joins(:categories).where(:categories => {:id => arr.sort})
	# 	@list = rs.find_all{|r| r.categories.map(&:id) == arr.sort}
	# 	@list.uniq
	# end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
	def new
		@restaurant = Restaurant.find(params[:restaurant_id])
		@star = Star.new
	end

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@star = @restaurant.stars.new
    	@star.user_id = current_user.id
		
		if @star.save
			respond_to do |format|
      		#flash[:notice] = "You have successfully starred this restaurant"
      		format.html { redirect_to restaurant_path(@restaurant) }
      		format.js
  			end
    	else
      		render 'star_restaurant'
    	end
	end

	def destroy
		@restaurant = Restaurant.find(params[:restaurant_id])
    	@star = Star.find(params[:id])
    	@star.destroy
    	respond_to do |format|
          #flash[:notice] = "You have successfully unstarred this restaurant"
          format.html {redirect_to restaurant_path(@restaurant)}
          format.js
        end
  end


end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
  	@x = 1
  	@title = "Index"
  end

  def show
  end

  def welcome
  	@title = "Welcome"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
  	#@restaurants = Restaurant.find_by_user_id(current_user) #this is the old way
  	@restaurants = Restaurant.where(:user => current_user) #using active relations, read about 'like'
  	@starred_by_user = Star.where(:user_id => current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def mark_required(object, attribute)
    "*" if object.class.validators_on(attribute).map(&:class).include? ActiveRecord::Validations::PresenceValidator
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
require 'uri'
module RestaurantsHelper
	def gmap_url(restaurant)
		url = "http://maps.googleapis.com/maps/api/staticmap?"
		url << "center=" + URI.escape(restaurant.full_address)
		url << "&markers=" + "color:red|" + URI.escape(restaurant.full_address)
		url << "&zoom=14"
		url << "&size=200x200"
		url << "&sensor=false"
		url << "&key=#{ ENV['GMAPS_API_KEY'] }"
		return url
	end

	def all_restaurants_gmap(restaurants)
		url = "http://maps.googleapis.com/maps/api/staticmap?"
		url << "center=" + URI.escape(@restaurants.first.zipcode)
		url << "&zoom=14"
		url << "&size=400x400"
		url << "&sensor=false"
		url << "&key=#{ ENV['GMAPS_API_KEY'] }"
		url << "&markers=color:red"

		@restaurants.each do |restaurant|
			url << '|' + "#{url_encode(restaurant.full_address)}" unless restaurant.full_address == ""
		end

		return url
	end

end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_search.html.erb
<!-- To Do -->

app/views/categories/index.html.erb
<h1>Restaurant Categories</h1>
<%= render 'search' %>
<ul>
	<% @categories.each do |category| %>
		<li><%= link_to category.name, category_path(category.id) %> <%= "(#{category.restaurants.count})"%></li>
	<% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %> Food Restaurants</h1>
<ul>
	<% @category.restaurants.each do |restaurant| %>
		<li><%= link_to restaurant.name, restaurant_path(restaurant.id) %></li>
	<% end %>

</ul>

app/views/stars/_star_restaurant.html.erb
<% if @restaurant.starred_by.include?(current_user) %>
<% @star = Star.where("restaurant_id = ? AND user_id = ?", @restaurant, current_user)%>

	<div id='remove_star'> Hey <%= current_user.name%> you have starred this restaurant.
	<%= link_to "Remove now", restaurant_star_path(@restaurant.id, @star.ids), method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
	</div>

<% else %>
	<div id = 'add_star'>Hey <%= current_user.name%> you haven't starred this restaurant. 
	<%= link_to "Star now", restaurant_stars_path(@restaurant.id), method: :post, id: "add_star", remote: true %>
	</div>
<% end %>

app/views/stars/create.js.erb
$('#add_star').hide().after('<%= j render("star_restaurant") %>');
$('#add_star').remove();

app/views/stars/destroy.js.erb
$('#remove_star').hide().after('<%= j render("star_restaurant") %>');
$('#remove_star').remove();

app/views/stars/new.html.erb
<%= render 'star_restaurant' %>

app/views/users/_owner.html.erb
<h1>Owner's dashboard</h1>


<table class='table table-striped'>
	 <caption>My restaurants</caption>
	<th>Name</th>
	<th> Stars</th>
	<th>Current Reservations</th>
	<th>View Reservations</th>

 <% @restaurants.each do |restaurant|  %>
 <tr>
 	<td><%= link_to restaurant.name, restaurant_path(restaurant) %></td>
 	<td> <%= restaurant.stars.count %> </td>
 	<td><%=restaurant.reservations.count %></td>
 	<td><%= link_to "Reservations",   restaurant_reservations_path(restaurant) %></td>
 </tr>
 
 <% end %>
</table>

app/views/users/_patron.html.erb
<h1><%= "#{current_user.name}'s user dashboard"%></h1> <%= "#{current_user.name}, you have starred the
followig restaurants" %> <ul>     <% @starred_by_user.each do |star| %>
<li><%= link_to star.restaurant.name, restaurant_path(star.restaurant) %></li>
<% end %> </ul>

app/views/users/dashboard.html.erb
<% if current_user.role == 'owner' %>
	<%= render 'owner' %>
<% else  %>
	<%= render 'patron' %>
<% end %>